### ISSUE TITLE
Uncaught Error: Element [identifier] is not known in this context.

### ISSUE THREAD

**Issue by juanmav** [highsource/ogc-schemas#101]
Hi, 

The follow example is falling: http://jsfiddle.net/juanmav/qedpng43/ 

First it is unmarshaling a string later is marshaling this object to a document and fails. I am not sure if it is a Jsonix problem or a ogc-schema problem. The example is made with ogc-schema 2.2.0 and jsonix 2.2.1 but also fails with ogc-schema 2.3.0 and jsonix 2.3.0.

Maybe I am missing something ?

Thanks in advance
JM

PD: With the ISO19139 profile fails too.

**Comment by highsource** [comment]
I'll take a look on the weekend.

**Comment by juanmav** [comment]
@highsource something can I do to to help to find the problem? I am trying to develop the CSW transactions at least I will like to get it done with the default profile.

**Comment by highsource** [comment]
Ok, the problem seems to be in the `mappingStyle:simplified`.

**Comment by highsource** [comment]
Here's the fixed version:

http://jsfiddle.net/qedpng43/2/

You were missing namespace mappings for `dc` and `dct`. They are required for the simplified mapping style.

**Comment by highsource** [comment]
Updated the docs:

https://github.com/highsource/jsonix/wiki/Simplified-Mapping-Style

**Comment by juanmav** [comment]
@highsource Thanks!!!!!! :D
