### ISSUE TITLE
isSet methods are no longer being generated

### ISSUE THREAD

**Issue by tastle** [highsource/ogc-schemas#102]
@highsource, we're updating from the 1.1.0 schemas to the 2.2.0 schemas.  (latest in Maven Central; did 2.3.0 not get pushed?)

We have a very difficult upgrade path because we made heavy use of the isSet method.  The new bindings have no longer have
```
generateIsSetMethod="true"
```
Is there a reason this was dropped?  If there is no good reason, would you be willing to accept a pull request with that adjustment?

**Comment by highsource** [comment]
I think this was just a migration glitch. I think this was not intentional so a PR would be ok.
Please also do this in w3c-schemas so that it is homogen across these projects.

**Comment by tastle** [comment]
Okay, thanks @highsource .  I'll have one of my guys take this on.

If accepted, would this be something that could be deployed to central fairly quickly?  (2.3.1?)

**Comment by highsource** [comment]
Yes.
