### ISSUE TITLE
WCS 1.0.0 bindings are broken

### ISSUE THREAD

**Issue by avautour** [highsource/ogc-schemas#104]
WCS 1.0.0 bindings are broken. They were fixed in the 1.1.0 under [OGC-50] (https://java.net/jira/browse/OGC-50), but are now generated with the official 3.1.1 GML schemas instead of the GML schema that ships with WCS 1.0.0.

As stated in that other issue, the main problem had to do with the origin element of the RectifiedGridType element. In [GML 3.1.1] (http://schemas.opengis.net/gml/3.1.1/base/grids.xsd), it is of type gml:PointPropertyType, yet in [GML for WCS 1.0.0] (http://schemas.opengis.net/wcs/1.0.0/gml4wcs.xsd), it is of type gml:PointType. The substitutionGroup of the RectifiedGrid element is also different in both schemas.

Using the official GML 3.1.1 schemas for WCS 1.0.0 results in the JAXB model producing XML that isn't schema compliant.

**Comment by highsource** [comment]
Should be fixed now. Thank you for the contribution.
