### ISSUE TITLE
Integrate with HyperJAXB3 for JPA annotations

### ISSUE THREAD

**Issue by spacebel** [highsource/ogc-schemas#107]
It would be really great to integrate this with HyperJAXB3 and so have JPA annotations in the generated classes.

**Comment by highsource** [comment]
I don't think it's a good idea.
First, not everybody needs this.
Next, JPA compatibility requires restucturing the generated Java code which does not really improve it.
Finally, many if not most of schemas don't allow good relational mapping.

So I don't think it's a good idea to do it in general in ogc-schemas.

**Comment by spacebel** [comment]
Ok, I agree :)
