### ISSUE TITLE
CSW profile ISO 19139-2 (http://www.isotc211.org/2005/gmi)

### ISSUE THREAD

**Issue by juanmav** [highsource/ogc-schemas#109]
Hi, 

I was wondering if exists the possibility to create the scripts to the ISO19139-2 profile? 

The ows.js can use the 19139 profile, an [example]https://github.com/juanmav/ows.js/blob/master/examples/learning.html#L191) and [jsfiddle](http://jsfiddle.net/juanmav/vqLz047f/9/) example with Jsonix.

Thanks in advance
JM

**Comment by highsource** [comment]
Could you please point to the schema URL?

**Comment by juanmav** [comment]
I am not sure but we found this:

- http://www.ngdc.noaa.gov/metadata/published/xsd/schema/
- http://sdi.eurac.edu/metadata/iso19139-2/schema/

**Comment by juanrapoport** [comment]
Hi, I vote for this.

We will use the ISO 19139-2 profile in a pycsw server (http://pycsw.org) to catalog products from a SAR satellite mission.
This profile allows to specify metadata about the satellite, sensor, processing algorithms, etc.
We think we could use Jsonix to convert the XML responses into JSON, so it would very useful if you could support it.

Really great work,
Thanks

**Comment by highsource** [comment]
Hi,

we'll implement this. What I'd need to know is:

* Where the schemas are located. @juanmav posted two links, I'm not quite sure those are official. Which one should I use?
* Do you happen to have examples of XML for testing?

Best wishes,
Alexey

**Comment by juanrapoport** [comment]
Hi!

Here you can read an explanation of the ISO 19139-2 XML implementation:

https://github.com/ISO-TC211/XML/wiki/The-History-of-the-gmi-Namespace#iso-19139-2-the-xml-implementation

In particular, it says:

> These schemas (those composing 19139-2) are available from in the ISO TC211 schema repository at http://www.isotc211.org/2005/gmi.

Or you can find the schemas here:

http://standards.iso.org/iso/19115/-2/gmi/1.0/

This is the content of the [gmi.xsd](http://standards.iso.org/iso/19115/-2/gmi/1.0/gmi.xsd) file (It basically imports the ISO 19139 schemas, and includes the files inside the gmi directory):

```xml
<xs:schema xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://standards.iso.org/iso/19115/-2/gmi/1.0" version="0.1">
    <!--
================================= Annotation ================================
-->
    <xs:annotation>
        <xs:documentation>
            This file was created by Ted Habermann during May 2015 to correct omissions (gmx, MI_EnvironmentalRecord) in existing gmi schema ======
        </xs:documentation>
    </xs:annotation>
    <!--
================================== Imports ==================================
-->
    <xs:import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" />
    <xs:import namespace="http://www.isotc211.org/2005/gco" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd" />
    <xs:import namespace="http://www.isotc211.org/2005/gss" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gss/gss.xsd" />
    <xs:import namespace="http://www.isotc211.org/2005/gmx" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd" />
    <xs:include schemaLocation="metadataEntitySet.xsd" />
    <xs:include schemaLocation="contentInformation.xsd" />
    <xs:include schemaLocation="dataQualityInformation.xsd" />
    <xs:include schemaLocation="spatialRepresentationInformation.xsd" />
</xs:schema>
```

And here is an example on how we (think) are going to catalog:

https://metadatos.conae.gov.ar/geonetwork/srv/spa/xml_iso19139?id=801


Hope this can help,
Thanks

**Comment by highsource** [comment]
Ok, I just want to recheck something.

This issue is only about `gmi`, not other iso19139 schemas, correct? So I can reuse the existing `iso19139` artifacts and compile GMI additionally, right?

**Comment by juanrapoport** [comment]
Right, is only about GMI, I think that compile GMI additionally will work fine.
I can help testing with our examples.

**Comment by highsource** [comment]
Work in progress right now.

**Comment by juanmav** [comment]
Awesome!!!

**Comment by highsource** [comment]
Implemented, please test:

https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/ISO19139_2_GMI_1_0.js

Tests:

https://github.com/highsource/ogc-schemas/tree/master/scripts/tests/ISO19139_2/GMI/1.0

@juanrapoport I had to correct a few problems with your XML. You had a wrong namespace for `gmi` and `gml`, I've corrected those.

Please test and let me know if it worked for you. More samples would be also good.

**Comment by juanmav** [comment]
Great work! I tested it and worked like a charm.

![19139-2](https://cloud.githubusercontent.com/assets/1016550/9920097/ab037b40-5ca7-11e5-8ab5-279d25a7d1c6.png)

**Comment by juanrapoport** [comment]
Excellent work!

Only one thing, you are right about gml namespace, but I think gmi namespace should be http://www.isotc211.org/2005/gmi, this is how it's defined in all the examples I've seen.

In this site http://www.ngdc.noaa.gov/metadata/ are a lot of examples using gmi, just mention a couple of lists with many files (each file is a catalogued item):
 * http://www.ngdc.noaa.gov/metadata/published/NOAA/NESDIS/NGDC/MGG/Hazards/iso/xml/
 * http://www.ngdc.noaa.gov/metadata/published/NOAA/NESDIS/NGDC/MGG/Geophysical_Models/iso/xml/

**Comment by juanmav** [comment]
+1 to the latest proposed changes by @juanrapoport

**Comment by highsource** [comment]
@juanmav @juanrapoport I've moved to http://www.isotc211.org/2005/gmi/gmi.xsd and added many XML examples from the links above. Two examples did not word on roundtrip - probably  because they use their own version of the schema.

This is actually completely crazy. Everybody's kinda doing their own versions - with their own namespace and a few changes. What is that? Is it standard or not? Even ISO publishes two sets with different namespaces. What is happening?

Anyway, please test if it works for you.

**Comment by highsource** [comment]
@juanmav @juanrapoport Could you please give it a try?

**Comment by juanmav** [comment]
@highsource It worked! https://github.com/juanmav/ows.js/commit/e68b6e9a04e61ed89c7f75c0559027a9236137b4

https://github.com/juanmav/ows.js/blob/ISO19139-2/examples/learning.html#L79-L98
https://github.com/juanmav/ows.js/blob/ISO19139-2/examples/learning.html#L206-L207

Thanks!

**Comment by highsource** [comment]
Perfect! Then I'll close the issue.

**Comment by juanmav** [comment]
@highsource about the modified versions of the standard we saw same as you, and we are struggling with that right now.

**Comment by juanrapoport** [comment]
@highsource Sorry for the delay.

I tested against several examples from here https://metadatos.conae.gov.ar/ (correcting gml namespaces) and it worked perfect.

This is incredible helpful, you're a superhero.

Thanks.

**Comment by highsource** [comment]
@juanmav @juanrapoport 2.5.1 is released now with ISO19139-2 bindings:

https://github.com/highsource/ogc-schemas/releases/tag/2.5.1

**Comment by juanmav** [comment]
@highsource Good! I will update ows.js dependencies!

Thanks!
