### ISSUE TITLE
Cannot unmarshall PropertyNameType of the Filter package

### ISSUE THREAD

**Issue by avautour** [highsource/ogc-schemas#111]
Cannot unmarshall PropertyNameType of the Filter package for both version 1.0.0 and 1.1.0.

Problem has to do with the generated code having the @XmlValue annotation for PropertyNameType.content and PropertyNameType deriving from the abstract ExpressionType.

> javax.xml.bind.JAXBException: Provider com.sun.xml.bind.v2.ContextFactory could
> not be instantiated: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 1
> counts of IllegalAnnotationExceptions
> @XmlValue is not allowed on a class that derives another class.
>         this problem is related to the following location:
>                at protected java.lang.String net.opengis.filter.v_1_0_0.PropertyNameType.content
>                at net.opengis.filter.v_1_0_0.PropertyNameType
>                at protected net.opengis.filter.v_1_0_0.PropertyNameType net.opengis.filter.v_1_0_0.PropertyIsLikeType.propertyName
>                at net.opengis.filter.v_1_0_0.PropertyIsLikeType
>                at @javax.xml.bind.annotation.XmlSeeAlso(value=[class net.opengis.filter.v_1_0_0.BinaryComparisonOpType, class net.opengis.filter.v_1_0_0.PropertyIsLikeType, class net.opengis.filter.v_1_0_0.PropertyIsNullType, class net.opengis.filter.v_1_0_0.PropertyIsBetweenType])
>                at net.opengis.filter.v_1_0_0.BinaryComparisonOpType
>                at public javax.xml.bind.JAXBElement net.opengis.filter.v_1_0_0.ObjectFactory.createPropertyIsLessThanOrEqualTo(net.opengis.filter.v_1_0_0.BinaryComparisonOpType)
>                at net.opengis.filter.v_1_0_0.ObjectFactory

Looking at the 1.x code for this project, those two versions had a modified version of PropertyNameType that was more than likely to work around this problem, although I cannot find anything concrete that confirms that was the case. That being said, I don't believe JAX-B should be generating code it cannot unmarshall.

See [the modified schema] (https://svn.java.net/svn/ogc~svn/ogc-schemas/trunk/filter/1.1.0/schema/src/main/resources/filter/1.1.0/expr.xsd) in the 1.x code,which has:
```xml
<!-- this is the corrected version of PropertyNameType -->
<xsd:complexType name="PropertyNameType" mixed="true">
	<xsd:complexContent mixed="true">
		<xsd:extension base="ogc:ExpressionType">
			<xsd:sequence>
				<xsd:any minOccurs="0"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>
<!-- this was the original (OGC) version of PropertyNameType -->
<!--
<xsd:complexType name="PropertyNameType" mixed="true">
	<xsd:complexContent mixed="true">
		<xsd:extension base="ogc:ExpressionType"/>
	</xsd:complexContent>
</xsd:complexType>
-->
```

**Comment by highsource** [comment]
Pretty likely. I think this was a case.
Would you mind adding test cases to reproduce?

**Comment by highsource** [comment]
I've moved inlined XML into a resource and now it's done. Thank you for your contribution.
