### ISSUE TITLE
CSW 2.0.2 GetCapabilitiesType service parameter invalid default value

### ISSUE THREAD

**Issue by trophies** [highsource/ogc-schemas#167]
I noticed that the generated code for the GetCapabilitiesType does not have the service parameter as a static final variable.  It also has an access method that defaults to the CSW namespace if the parameter is null.  However, the CSW schema defines the service parameter as with a fixed value of *"CSW"* (see http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd).

I checked the WCS 2.0 GetCapabilitiesType generated code and it has:

    @XmlAttribute(name = "service", required = true)
    public final static String SERVICE = "WCS";

Which is what I would expect (haven't checked other schemas to see what they generate).  The CSW code is also missing the *required=true* attribute on the @XmlAttribute annotation.

**Comment by highsource** [comment]
There was some reason for this which I can't remember at the moment.

**Comment by trophies** [comment]
I seem to recall noticing this before and maybe discussing it with @tastle, but don't remember what the outcome was.

I searched to see if a bug was filed previously but couldn't find one.  The CSW GetCapabilitiesType is separate from the other response type's (it extends the OWS 1.0 common GetCapabilitiesType, where the rest of them have their own RequestBaseType they extend), but I would think JAXB would still make that a static final parameter due to how it's defined in the schema unless it was overridden in the xjb file, but it doesn't appear to be that I can see.

I looked at some of the other generated classes for other OWS's and the only other one I could find that did the same thing was the GetcapabilitiesType for the WFS 1.1.0, which also extends the OWS 1.0 common GetCapabilitiesType class.

**Comment by tastle** [comment]
@trophies and I talked this through earlier today, so I'm going to summarize a bit.

JAXB is doing exactly what the schema is telling it to do.  The below is taken from the CSW-discovery.xsd

```XML
   <xsd:complexType name="GetCapabilitiesType" id="GetCapabilitiesType">
      <xsd:annotation>
         <xsd:documentation>
            Request for a description of service capabilities. See OGC 05-008 
            for more information.
         </xsd:documentation>
      </xsd:annotation>
      <xsd:complexContent>
         <xsd:extension base="ows:GetCapabilitiesType">
            <xsd:attribute name="service" type="ows:ServiceType" use="optional"
               default="http://www.opengis.net/cat/csw"/>
         </xsd:extension>
      </xsd:complexContent>
   </xsd:complexType>
```

It looks like poor modelling and probably an outright mistake.  If you look at the OWS 1.0.0 owsGetCapabilities.xsd, I think it's pretty clear on what the value of a ServiceType should be.

```XML
	<simpleType name="ServiceType">
		<annotation>
			<documentation>Service type identifier, where the string value is the OWS type abbreviation, such as "WMS" or "WFS". </documentation>
		</annotation>
		<restriction base="string"/>
	</simpleType>
```

What I'll do is make an inquiry about this to the OGC and share the issue with @trophies .  If something comes out of it, I'll create a new issue in this project to pick up schema updates or apply a patch and cite this issue.

**Comment by tastle** [comment]
@trophies, after discussing this with the authors, I have 16-054r2 pending approval where we changed the default value of the string.  Once that's through, I'd just expect to make a new build of the project to pick this up.

If you see this happening before I do, create a ticket about making a new release to pick up the schemas change.
