### ISSUE TITLE
More modular approach to schemas?

### ISSUE THREAD

**Issue by bartvde** [highsource/ogc-schemas#170]
I was using the following in a project:

```
import {Jsonix} from 'jsonix';
import {XSD_1_0, XLink_1_0} from 'w3c-schemas';
import {OWS_1_0_0, Filter_1_1_0, SMIL_2_0, SMIL_2_0_Language, GML_3_1_1, WFS_1_1_0} from 'ogc-schemas';
```

However this pulls in the complete ```ogc-schemas``` and ```w3c-schemas``` in the final build.

Could we make ```ogc-schemas``` more modular, maybe an approach similar to https://github.com/Turfjs/turf ? See also here for details: https://github.com/Turfjs/turf/pull/311

Thoughts?

**Comment by highsource** [comment]
You can actually go deeper and import individual schemas instead of the root object.

**Comment by highsource** [comment]
But we definitely can rework the dependencies.

**Comment by bartvde** [comment]
Yes this works for some setups but not the one I am using now (browserify with ES6):

```
Error: Cannot find module './node_modules/ogc-schemas/lib/OWS_1_1_0.js' from '/Users/bartvandeneijnden/opengeo/git/sdk/js/components'
    at /Users/bartvandeneijnden/opengeo/git/sdk/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/bartvandeneijnden/opengeo/git/sdk/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by bartvde** [comment]
False alarm, didn't use the right path ;-) more coffee ....

**Comment by bartvde** [comment]
This is definitely sufficient for now.

**Comment by WillieMaddox** [comment]
@bartvde I am running into this exact same issue.  what did you do to your "path" to make this work?

**Comment by bartvde** [comment]
just import the individual files instead
