### ISSUE TITLE
Setting  attribute with concrete element

### ISSUE THREAD

**Issue by abiuan** [highsource/ogc-schemas#171]
Hello,
I'm using ogc-schemas to produce O&M files.

Setting phenomenonTime I cannot use a concrete type: the signature of _TimeObjectPropertyType.setAbstractTimeObject()_ method is _setAbstractTimeObject(JAXBElement<AbstractTimeObjectType> value)_.
Should be _setAbstractTimeObject(JAXBElement<? extends AbstractTimeObjectType> value)_?

Similiar problem setting shape in featureOfInterest:
_ShapeType.setAbstractGeometry(JAXBElement<AbstractGeometryType> value)_
should be _setAbstractGeometry(JAXBElement<? extends AbstractGeometryType> value)_?

Regards

Alberto

**Comment by highsource** [comment]
What actually does not work? I mean, we can discuss whether these method signatures are pretty or not, but is there actually a technical problem?

The thing is. this is the way XJC generates code. It's not in the scope of this project to improve XJC in any way - unless there's no other workaround. Could you please show the code which does not work right now and we'll see if there's a blocker.

**Comment by abiuan** [comment]
I have to produce the following xml:

```
<om:phenomenonTime>
  <gml:TimeInstant>
  ...
  </gml:TimeInstant>
</om:phenomenonTime>

```
As TimeInstant is a descendent class of AbstractTimeObjectType, what I'm expeting to do in Java is:
```
OMObservationType observationType;
TimeObjectPropertyType timeStamp = omObjectFactory.createTimeObjectPropertyType();

timeStamp.setAbstractTimeObject(gmlObjectFactory.createTimeInstant(...));

observationType.setPhenomenonTime(timeStamp);
```
But _TimeObjectPropertyType.setAbstractTimeObject()_ accept only a variable of type _JAXBElement\<AbstractTimeObjectType\>_ and not  _JAXBElement\<? extends AbstractTimeObjectType\>_ hence I'm only able to write:
`timeStamp.setAbstractTimeObject(gmlObjectFactory.createAbstractTimeObject(...));`
producing the following XML:
```
<om:phenomenonTime>
        <gml:AbstractTimeObject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="gml:TimeInstantType" gml:id="t0">
            <gml:timePosition>2015-04-16T03:06:00Z</gml:timePosition>
        </gml:AbstractTimeObject>
</om:phenomenonTime>
```
that I think is an error because gml:AbstractTimeObject is declared abstract in the schema.

Regards

Alberto

**Comment by highsource** [comment]
Generics are erased anyway so it's actually safe to cast. But I'll look into it.

**Comment by highsource** [comment]
Fixed:

```
    public JAXBElement<? extends AbstractTimeObjectType> getAbstractTimeObject() {
        return abstractTimeObject;
    }
    public void setAbstractTimeObject(JAXBElement<? extends AbstractTimeObjectType> value) {
        this.abstractTimeObject = value;
    }
```
