### ISSUE TITLE
No WFS capabilities

### ISSUE THREAD

**Issue by jaberu** [highsource/ogc-schemas#172]
in ogc-schemas/wfs/1.0.0/pom.xml the mapping for the wfs capabilities is not present:
http://schemas.opengis.net/wfs/1.0.0/WFS-capabilities.xsd

I'm wondering if there is a reason for that. The same is true for the other wfs versions.

**Comment by highsource** [comment]
> The same is true for the other wfs versions.

What exactly do you mean? `WFSCapabilities` are generated in 1.1.0 and 2.0. Not in 1.0.0, true.

**Comment by highsource** [comment]
Should be fixed now, `WFSCapabilities` also generated for WFS 1.0.0.

**Comment by jaberu** [comment]
Thanks for quick response.
Is there any plans to release 2.6.2 in any public maven repository?

**Comment by highsource** [comment]
Probably after #168.

**Comment by highsource** [comment]
Does not work yet. ;(

**Comment by highsource** [comment]
Now it does.
