### ISSUE TITLE
wmts-v_1_0 - 2.6.1 - TileMatrix.getTopLeftCorner List<Double> contains String values

### ISSUE THREAD

**Issue by shruda** [highsource/ogc-schemas#173]
Hi,
if I try to get a double value from the TileMatrix's TopLeftCorner list, than I'll get a ClassCastException:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double

    double value = tileMatrix.getTopLeftCorner().get(0);

Best Regards,
Steve

**Comment by highsource** [comment]
Reproduced. This is due to:

https://java.net/jira/browse/JAXB-986

**Comment by highsource** [comment]
Should be fixed now. Please build `wmts-v_1_0` in the current snapshot and try again.
