### ISSUE TITLE
require?

### ISSUE THREAD

**Issue by WillieMaddox** [highsource/ogc-schemas#178]
Hello,

In the following code snippet, where does the "require" function come from?
```javascript
var WFS_1_1_0 = require('ogc-schemas').WFS_1_1_0;
```

Thanks,

**Comment by WillieMaddox** [comment]
Nevermind. I answered my own question.

Node.js

**Comment by highsource** [comment]
In builds `require` is from Node.js. In the runtime you can also get it from module loader like System.js.
