### ISSUE TITLE
INSPIRE schemata binding

### ISSUE THREAD

**Issue by abiuan** [highsource/ogc-schemas#181]
I need to use an INSPIRE schema (http://inspire.ec.europa.eu/schemas/). This schema cascading refers to other 2 INSPIRE schemata.
INSPIRE schemata are extensions of OGC ones.
I did a try without success, to produce java binding classes.
Could you give some suggests and rules on how can I deal this problem?

**Comment by highsource** [comment]
I've started the [inspire-schemas](https://github.com/highsource/inspire-schemas) project a while ago.

Unfortunately, there's no easy solution to this. You have to go through all the relevant schemas/dependencies and add them one by one. This project as well as the mentioned [inspire-schemas](https://github.com/highsource/inspire-schemas) project have examples how to do this, but there's no complete how-to guide.

Check the [inspire-schemas](https://github.com/highsource/inspire-schemas) project, file issues for schemas you need and try to implement it on your own following conventions/structures you see in already compiled schemas. Send me pull requests, I'll review/apply/correct them as needed.

One thing I have to say is that I myself won't set a goal to compile all the INSPIRE schemas (as we did in this project for OGC schemas). They are just too many and I personally don't have the necessity for my business. However I can help by reviewing/correcting pull requests/answering specific questions if you (or anyone) would try to compile INSPIRE schemas.

Please file issues per schema in the [inspire-schemas](https://github.com/highsource/inspire-schemas) project.

**Comment by highsource** [comment]
Closing as not in scope here.
