### ISSUE TITLE
WCS_1_1 bug when unmarshalling WCS version 1.1.1 xml

### ISSUE THREAD

**Issue by PhilippePinheiroLIST** [highsource/ogc-schemas#198]
When unmarshalling a WCS version 1.1.1 xml I get the following error message 

Error: Element [{http://www.opengis.net/wcs/1.1.1}wcs:Capabilities] could not be unmarshalled as is not known in this context and the property does not allow DOM content.

Here is my code : 

var url = "http://geoweb2.sbg.ac.at/geoserver/wms?SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.1.1";
var context = new Jsonix.Context([XLink_1_0, OWS_1_1_0, GML_3_1_1, SMIL_2_0,SMIL_2_0_Language, WCS_1_1]);
        var unmarshaller = context.createUnmarshaller();
            unmarshaller.unmarshalURL(url, function(result){
            console.log(result.value);
            callback(result.value);
        });

**Comment by highsource** [comment]
This does not work as the XML is of version WCS 1.1.1, not 1.1.
Currently only 1.1 is supported, not 1.1.1.
1.1.1 also does not seem to be the OGC standard:

**Comment by highsource** [comment]
This should be fixed now, added WCS_1_1_1. Your XML file roundtrips OK now.
