### ISSUE TITLE
How to generate PO.js with *.jsonix.jxb and *.jxb  files

### ISSUE THREAD

**Issue by juanmav** [highsource/ogc-schemas#41]
Hi, 

I can't figure out how generate the Javascript mapping from the *.jxb files (I am trying with CSW files). Already downloaded the schema compiler and the xjb files.

The command I trying is:

```
java -jar jsonix-schema-compiler-full-2.0.0.jar -b csw-v_2_0_2.xjb
```

The output error:

```
Exception in thread "main" com.sun.tools.xjc.BadCommandLineException: grammar is not specified
	at com.sun.tools.xjc.Options.parseArguments(Options.java:809)
	at org.hisrc.jsonix.JsonixMain.main(JsonixMain.java:89)
```

If anyone can help will be appreciated.

Thanks in advance
JM

**Comment by juanmav** [comment]
@highsource 

Now I executed the following command:

```
java -jar jsonix-schema-compiler-full-2.0.0.jar -b csw-v_2_0_2.xjb -d ./ -p CSW "http://schemas.opengis.net/csw/2.0.2/csw.xsd"
```

But it is throwing this error:

```
[ERROR] Property "Title" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 232 of http://www.w3.org/1999/xlink.xsd

[ERROR] The following location is relevant to the above error
  line 219 of http://www.w3.org/1999/xlink.xsd

[ERROR] Property "Title" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 261 of http://www.w3.org/1999/xlink.xsd

[ERROR] The following location is relevant to the above error
  line 246 of http://www.w3.org/1999/xlink.xsd
```

Any ideas?

Thanks in advance
JM

**Comment by juanmav** [comment]
Still working.

I added to the jbx file the following bindings to avoid the previous conflict:

```XML
<jaxb:bindings schemaLocation="http://www.w3.org/1999/xlink.xsd" node="//xs:schema">
        <jaxb:bindings node=".//xs:attribute[@name='title']">
            <jaxb:property name="title1"/>
        </jaxb:bindings>
</jaxb:bindings>
```

But now it is throwing this error:

```
Exception in thread "main" java.lang.IllegalArgumentException: The validated collection is empty
	at org.jvnet.jaxb2_commons.lang.Validate.notEmpty(Validate.java:23)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMElementRefsPropertyInfo.<init>(CMElementRefsPropertyInfo.java:37)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.createElementRefsPropertyInfo(CMInfoFactory.java:371)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.createPropertyInfo(CMInfoFactory.java:291)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:217)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:175)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:137)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:197)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:171)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:137)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:408)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.createElementRefPropertyInfo(CMInfoFactory.java:353)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.createPropertyInfo(CMInfoFactory.java:289)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.getTypeInfo(CMInfoFactory.java:217)
	at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMInfoFactory.createModel(CMInfoFactory.java:116)
	at org.hisrc.jsonix.JsonixMain.execute(JsonixMain.java:132)
	at org.hisrc.jsonix.JsonixMain.main(JsonixMain.java:92)
```

**Comment by highsource** [comment]
Just came to it, give me a few minutes...

**Comment by highsource** [comment]
Ok, I somewhat got it. But it just does not work well from the command-line at the moment.

* First, I had to make all the absolute URLs in imports relative. It did not work because of https://java.net/jira/browse/JAXB-1046. This is not good and must be fixed.
* Next, add the `*.xjb` files for the relevant schemas (main schema and its imports).
* Code generation is as follows:

```
java -jar lib/jsonix-schema-compiler-full-2.3.1.jar
 -catalog schemas/catalog.cat
 schemas/ogc/csw/2.0.2/csw.xsd
 schemas/w3c/1999/xlink.xsd
 -b schemas
 -d mappings
```

This generates JS mappings in `mappings`. (By the way these mappings are also available [here](https://github.com/highsource/ogc-schemas/tree/master/scripts/lib), you can use them pregenerated.)

I guess you're probably interested in a single file for CSW 2.0.2 so I reworked the configuration a bit:

```xml
	<jaxb:bindings 
		schemaLocation="ogc/csw/2.0.2/csw.xsd" 
		node="/xs:schema">

		<jsonix:module name="CSW_2_0_2_Full">
			<jsonix:mapping package="net.opengis.csw.v_2_0_2" name="CSW_2_0_2"/>
			<jsonix:mapping package="org.hisrc.dc.elements.v_1_1" name="DC_1_1">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="org.hisrc.dc.terms" name="DCT">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="net.opengis.filter.v_1_1_0" name="Filter_1_1_0">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="net.opengis.gml.v_3_1_1" name="GML_3_1_1">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="org.w3.smil.v_2_0" name="SMIL_2_0">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="org.w3.smil.v_2_0.language" name="SMIL_2_0_Language">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="net.opengis.ows.v_1_0_0" name="OWS_1_0_0">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
			<jsonix:mapping package="org.hisrc.w3c.xlink.v_1_0" name="XLink_1_0">
				<jsonix:includes>
					<jsonix:dependencies-of-mapping name="CSW_2_0_2"/>
				</jsonix:includes>
			</jsonix:mapping>
		</jsonix:module>

	</jaxb:bindings>
```

This produces a single `CSW_2_0_2_Full.js` mapping file which contains everything you should need for CSW 2.0.2.

**Comment by highsource** [comment]
I'll file a few follow-up issues tomorrow:

* Compiling absolute URLs from the command line does not work (but works in Maven) in `jsonix-schema-compiler` (relevant to JAXB-1044).
* Fix JAXB-1045, JAXB-1046. This will probably require a patch for `jaxb-xjc`. This is necessary to avoid the need to change absolute URLs into relative URLs.

**Comment by highsource** [comment]
@juanmav Please see this demo:

https://github.com/highsource/ogc-schemas/tree/master/demos/csw/2.0.2

This is the best which which works at the moment from the command line.
When issues above are resolved, there'll be no need to change absolute URLs in relative URLs.

**Comment by juanmav** [comment]
@highsource thank you very much! I will try it!

**Comment by juanmav** [comment]
@highsource I just made a little [jsfiddle] (http://jsfiddle.net/juanmav/08bdzkwz/) to test the `CSW_2_0_2_Full.js`.

I just test a single getRecords but it is returning the following error:

```javascript
{
stack: (...), 
message: "Could not find element declaration for the element…ww.opengis.net/cat/csw/2.0.2}GetRecordsResponse]."
}
```

I don't know what i am doing wrong, any suggestions? I am really sorry for the constants questions.... :disappointed: 

Thanks in advance
JM

**Comment by highsource** [comment]
First, should look like this:

http://jsfiddle.net/08bdzkwz/2/

You should create the contex for mappings exported by the module:

var context = new Jsonix.Context([OWS_1_0_0, DC_1_1, DCT,
XLink_1_0, CSW_2_0_2]);

***
But there seems to be a bug, as this:

var context = new Jsonix.Context([CSW_2_0_2, OWS_1_0_0, DC_1_1, DCT,
XLink_1_0]);

fails with an unknown type error.

**Comment by highsource** [comment]
And don't worry about asking question and so on. The whole thing is quite
new so your feedback and questions are very important to shape and polish
the library.

I'd be grateful for you patience in case something does not work. Things
will be fixed, I just need some time for that.

**Comment by highsource** [comment]
See #42 and #43.
I think this one can be closed now.
