### ISSUE TITLE
Add Filters_..._Full Modules

### ISSUE THREAD

**Issue by juanmav** [highsource/ogc-schemas#46]
Create Filters Full Modules. it should be optimized with GML

**Comment by highsource** [comment]
See tomkralidis/csw4js#1.

**Comment by highsource** [comment]
The `CSW_2_0_2_Full` now also includes `Filter_1_1_0` and (only the relevant parts of) `GML_3_1_1`. Please give it a try.

Please see [this test](https://github.com/highsource/ogc-schemas/blob/master/scripts/tests/CSW/2.0.2/CSW_2_0_2_Full.js#L2-L13). Everything is coming from a single module `CSW_2_0_2_Full`.
