### ISSUE TITLE
Support for Web Map Context (WMC)

### ISSUE THREAD

**Issue by bartvde** [highsource/ogc-schemas#48]
I couldn't find it here: https://github.com/highsource/ogc-schemas/tree/master/scripts/lib

This just came up on ol3-dev

https://groups.google.com/d/msg/ol3-dev/pcsivaZS-ks/20k5dY-Yw2sJ

**Comment by highsource** [comment]
Is it a duplicate for #47?

**Comment by bartvde** [comment]
No I think it's different.

#47 is OWS Context version 1.0.0 AFAIK

This refers to:

http://schemas.opengis.net/context/1.0.0/context.xsd

and/or version 1.1.0

**Comment by highsource** [comment]
Yes, you're right. I wonder what OWC is then.

**Comment by bartvde** [comment]
it's "OGC Web Services Context Atom Standard" see: http://schemas.opengis.net/owc/ReadMe.txt for more info

**Comment by highsource** [comment]
Oha, RelaxNG. Never compiled that but should work.

**Comment by highsource** [comment]
WMC 1.0.0 and 1.1.0 done, with tests.

**Comment by bartvde** [comment]
thanks @highsource
