### ISSUE TITLE
Support WPS 2.0.0

### ISSUE THREAD

**Issue by nuest** [highsource/ogc-schemas#49]
Schemas are final but sadly not up on the OGC website yet, but you can get a preview here: https://github.com/bpross-52n/common-xml/tree/284120f4f483409d420896e1a789f4a02a7cf3a0/52n-ogc-schema/src/main/resources/META-INF/xml/wps/2.0

**Comment by highsource** [comment]
Sure. :)

**Comment by highsource** [comment]
Done.

**Comment by highsource** [comment]
Mappings:

https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/WPS_2_0.js

Tests:

https://github.com/highsource/ogc-schemas/tree/master/scripts/tests/WPS/2.0
