### ISSUE TITLE
Trouble building OGC WAMI Services

### ISSUE THREAD

**Issue by JonathanTParker** [highsource/ogc-schemas#50]
I am attempting to build OGC Best Practices schema for WAMI Services: Dissemination Services for Wide Area Motion Imagery - Best Practice.
OGC 12-032r2.
Best Practices List: http://www.opengeospatial.org/standards/bp
Document: https://portal.opengeospatial.org/files/?artifact_id=50486
and             http://www.opengis.net/doc/bp/wami/1.0

Associated Schemas: http://bp.schemas.opengis.net/12-032r2/wami/xsd/

Directed to this site from: https://java.net/projects/ogc/lists/users/archive/2015-03/message/2

My goal is to convert our existing WAMI server software to support this Best Practices schema.
I am using NetBeans 7.3 and 8.0.2, but am not very familiar with OGC JAXB issues, MAVEN, or GitHub.

Thanks.

**Comment by JonathanTParker** [comment]
I succeeded in building the W3C Schemas Project on windows in NetBeans 8.0.2. Attempted to build the OGC OWS project in the same environment, as you suggested.  The build did not make it very far.  What am I missing?
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
cd C:\Users\parkerjon\Desktop\AIMES\GIT\ogc-schemas\ows; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.7.0_21" cmd /c "\"\"C:\\Program Files\\NetBeans 8.0.2\\java\\maven\\bin\\mvn.bat\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.0.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 install\""
Scanning for projects...
------------------------------------------------------------------------
Reactor Build Order:
OGC OWS 1.0.0
OGC OWS 1.1.0
OGC OWS 2.0
OGC OWS
------------------------------------------------------------------------
Building OGC OWS 1.0.0 2.1.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ ows-v_1_0_0 ---

--- maven-jaxb2-plugin:0.12.1:generate (xjc) @ ows-v_1_0_0 ---
Error resolving dependency resource [Dependency {groupId=org.jvnet.ogc, artifactId=ogc-schemas, version=2.1.0-SNAPSHOT, type=jar, classifier=null, resource=ogc/catalog.cat}].
Failed to resolve systemId [maven:org.jvnet.ogc:ogc-schemas:jar::2.1.0-SNAPSHOT!/ogc/catalog.cat] as dependency resource. Returning parent resolver result [null].
------------------------------------------------------------------------
Reactor Summary:
OGC OWS 1.0.0 ..................................... FAILURE [2.105s]
OGC OWS 1.1.0 ..................................... SKIPPED
OGC OWS 2.0 ....................................... SKIPPED
OGC OWS ........................................... SKIPPED
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.550s
Finished at: Wed Mar 18 16:54:53 EDT 2015
Final Memory: 7M/121M
------------------------------------------------------------------------
Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.1:generate (xjc) on project ows-v_1_0_0: Error parsing catalog [maven:org.jvnet.ogc:ogc-schemas:jar::2.1.0-SNAPSHOT!/ogc/catalog.cat]. unknown protocol: maven -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by highsource** [comment]
You need to build the whole project, looks like you only tried OWS. Please post the mvn clean install -X log.

**Comment by highsource** [comment]
@JonathanTParker I've compiled WAMI versions 1.0.0, 1.0.1 and 1.0.2, now checked in. Try `mvn clean install` on the whole project. In case of problems please post `mvn -X -e clean install` log.

Tests for JS part pending.

**Comment by JonathanTParker** [comment]
Thanks a lot @highsource.  I was able to use the maven command line to build ogc-schemas with no problem.  Your suggestions hint that I may be using the wrong strategy for download and build, which is why I tried command line maven directly. 

However, my first inclination was to build directly in NetBeans with the maven plugin (which worked for W3C). This does not work for OGC, as seen below.  I get the same error for OGC Schemas Project as I do with OGC Schemas.  Can you suggest a cause for this? I would like to know that I have my environment set up correctly.

Debug "-e" BUILD FAILURE
-------------------------------------------------------------------
Applying patch: ogc.patch
Total time: 10.585s
Finished at: Wed Mar 18 23:26:47 EDT 2015
Final Memory: 8M/123M
Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.1.1:apply (patch-sources) on project ogc-schemas: Patch command failed with exit code 1 for ogc.patch. Please see console and debug output for more information. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.1.1:apply (patch-sources) on project ogc-schemas: Patch command failed with exit code 1 for ogc.patch. Please see console and debug output for more information.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Patch command failed with exit code 1 for ogc.patch. Please see console and debug output for more information.
	at org.apache.maven.plugin.patch.ApplyMojo.applyPatches(ApplyMojo.java:459)
	at org.apache.maven.plugin.patch.ApplyMojo.execute(ApplyMojo.java:299)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Re-run Maven using the -X switch to enable full debug logging.
For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by highsource** [comment]
Please do a `git fetch` first. Schemas are patched against the [genesis](https://github.com/highsource/ogc-schemas/tree/genesis) branch, so you have to have it actual in your local copy. I think I'll rework the patching process so that the the [genesis](https://github.com/highsource/ogc-schemas/tree/genesis) would no longer be needed. At the moment, it is quite cumbersome. Does not work reliably.

Consider using `mvn -X clean install` to produce a verbose log. This often gives clues.

**Comment by JonathanTParker** [comment]
Looks like the netbeans command line did not have the 'patch' command.  Sad. It also did not have 'node' command.  I updated user PATH to reference the npm, maven, and git bin directories and all is now running fine in NetBeans.  Although I am still not sure that is the place I should be building W3C or OGC.

Here are the steps that I went through.  @highsource, does it represent your suggestions?
Install maven: http://maven.apache.org/download.cgi
Install git: http://git-scm.com/download/win
Install nodejs 64 bit: https://nodejs.org/
Install netbeans EE: https://netbeans.org/community/releases/80/install.html
-git, maven plugins?
Add to windows $PATH variable for npm, node, and patch: C:\Users\parkerjon\AppData\Roaming\npm;C:\Program Files\Apache Software Foundation\apache-maven-3.3.1\bin;C:\Program Files (x86)\Git\bin
At Git command line (‘git fetch’ later to keep up to date):
-git clone https://github.com/highsource/w3c-schemas
-git clone https://github.com/highsource/ogc-schemas
Build externals in git command line (or NetBeans maven project)
-cd w3c-schemas; mvn clean install;
-cd ogc-schemas; mvn clean install;

**Comment by highsource** [comment]
You also need the  `patch` on the command line. Normally it is enough to add your `git/bin` to the `PATH`, there's a `patch` tool there.

An make sure first it works from the command line before going to IDEs. I'm using Eclipse so I can't really help much with NetBeans. And I normally build everything from the command line.

**Comment by JonathanTParker** [comment]
Thanks for integrating the WAMI schema. Huge help!

**Comment by highsource** [comment]
Is it solved for you now? I'd close the issue then.

**Comment by highsource** [comment]
Ok, I think this should be solved by now, I'm closing the issue.

**Comment by JonathanTParker** [comment]
Trying to test this today.  I am not building my service with Maven.  How do I determine all the dependencies? I need to build and run on a standalone development server.  Looks like the needed discrepancies are not included in wami-v_1_0_0-2.1.0-SNAPSHOT.jar or ows-v_2_0-2.1.0-SNAPSHOT.jar.  What is jsonix-shema-compiler-full-2.3.1.jar, found in the demos folder?

**Comment by JonathanTParker** [comment]
Would it make sense for the ogc build process to copy all dependent jars to a target folder?

**Comment by highsource** [comment]
Oh. Not using Maven? Try `mvn dependency:tree` in `wami/1.0.2` folder. You'll get:

```
[INFO] org.jvnet.ogc:wami-v_1_0_2:jar:2.1.0-SNAPSHOT
[INFO] +- org.jvnet.ogc:ows-v_2_0:jar:2.1.0-SNAPSHOT:compile
[INFO] |  \- org.hisrc.w3c:xlink-v_1_0:jar:1.0.4-SNAPSHOT:compile
[INFO] +- org.jvnet.jaxb2_commons:jaxb2-basics-runtime:jar:0.9.2:compile
[INFO] +- org.glassfish.jaxb:jaxb-runtime:jar:2.2.11:provided
[INFO] |  +- org.glassfish.jaxb:jaxb-core:jar:2.2.11:provided
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.2.11:provided
[INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.2.11:provided
[INFO] |  |  \- com.sun.istack:istack-commons-runtime:jar:2.21:provided
[INFO] |  +- org.jvnet.staxex:stax-ex:jar:1.7.7:provided
[INFO] |  \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.13:provided
[INFO] \- junit:junit:jar:4.11:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```

You don't need test dependencies in the runtime. Only `compile` and `provided`, so you have the list.

> Would it make sense for the ogc build process to copy all dependent jars to a target folder?

In principle, yes. In some projects I do "sample" projects which include Ant distributions. Those do have all the dependencies in a folder like `lib`. Like this project, for instance:

https://github.com/highsource/jaxb2-basics/releases

If you wish, you can file a new issue for this.

> What is jsonix-shema-compiler-full-2.3.1.jar, found in the demos folder?

This is a long story. It's this one:

https://github.com/highsource/jsonix-schema-compiler

Generates XML<->JS mappings. In demos, well, for demo purposes. Otherwised used via Maven during the build process. You can safely ignore it.

**Comment by JonathanTParker** [comment]
My initial testing was successful and all wami/ows schemas that I touched marshalled properly.  Thanks.
