### ISSUE TITLE
ISO 19139 (2006_05_04)

### ISSUE THREAD

**Issue by tastle** [highsource/ogc-schemas#56]
We use the ISO 19139 XML models to work with Service metadata.

This depends on the addition of GML 3.2.0.

(I'm not sure if this is the right place to file this issue, as I haven't seen an "ISO schemas" repository, but I've noticed you had some repositories for w3c, oasis, etc.)

**Comment by highsource** [comment]
GML 3.2.0 (#58) appears to be needed for this. GML 3.2.0 and GML 3.2.1 have different namespaces.
