### ISSUE TITLE
ISO 19139 (2007_04_17)

### ISSUE THREAD

**Issue by tastle** [highsource/ogc-schemas#57]
We use the ISO 19139 XML models to most of our dataset metadata.

(I'm not sure if this is the right place to file this issue, as I haven't seen an "ISO schemas" repository, but I've noticed you had some repositories for w3c, oasis, etc.)

**Comment by highsource** [comment]
Do you mean this one?

https://github.com/highsource/ogc-schemas/tree/master/iso19139/20070417

**Comment by tastle** [comment]
Ooops, sorry!  The first night I did the review, I seen this.  Then by the next day, I forgot.  :)

**Comment by highsource** [comment]
No problem. :)
