### ISSUE TITLE
Missing OWS factory.createExceptionReport

### ISSUE THREAD

**Issue by JonathanTParker** [highsource/ogc-schemas#59]
There is no factory method create*() which returns JAXBElement<ExceptionReport>.

Further, I am not sure the the following existing method is nececcary:
JAXBElement<ExceptionType>createException(ExceptionType)

I was getting lost in all the classes, so I include the following for clarities sake.

From: 12-032r2_WAMI_Services_Dissemination_Services_for_Wide_Area_Motion_Imagery__-_Best_Practice.pdf
In section 12:Exception Handling
The element ExceptionReport begins each Exception Report.
An ExceptionReport shall contain two Attributes, version and xml:lang.
An ExceptionReport shall contain one or more Exception elements.
An Exception element shall contain two attributes, exceptionCode and locator and one element ExceptionText.
The XML schema document for an exception report is available at the OGC website in the document names owsExceptionReport.xsd.

**Comment by highsource** [comment]
Confirmed, [`owsExceptionReport.xsd`](https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources/ogc/ows/2.0/owsExceptionReport.xsd) is simply missing in [`owsAll.xsd`](https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources/ogc/ows/2.0/owsAll.xsd#L23-L28).

Oh, well, OGC Schemas...

**Comment by highsource** [comment]
I've just checked what's generated. Everything seems correct. You should be getting the following methods:

```
public ExceptionReport createExceptionReport() { ...}
public ExceptionType createExceptionType() { ... }
public JAXBElement<ExceptionType> createException(ExceptionType value) { ... }
```

So I'm not quite sure what you're missing.

**Comment by highsource** [comment]
Would you please check this because I'd like to release 2.1.0 soon.

**Comment by JonathanTParker** [comment]
I will be looking for:
public JAXBElement<ExceptionReport> createExceptionReportSomethingOrOther(ExceptionReport)

**Comment by highsource** [comment]
You should do something like:

```java
ExceptionReport exceptionReport = of.createExceptionReport();
ExceptionType exceptionType = of.createExceptionType();
exceptionReport.getException().add(exceptionType);
exceptionType.getExceptionText().add("Strange things happen on a sunday night.");
```

You could then marshall `exceptionReport` as it has `@XmlRootElement`. You don't need an extra `JAXBElement` for this.

**Comment by JonathanTParker** [comment]
Aaaaaah.  So what is different from what was present before?  I have to leave for a couple hours.  Will test whatever you suggest when I get back.

**Comment by highsource** [comment]
Not quite sure what you mean by:

> So what is different from what was present before?

Which difference (between what and what) do you mean?

I think I'll round up now, it's almost midnight.

**Comment by JonathanTParker** [comment]
The exceptionReport code above worked as your suggested.  Thanks.

I see the code you changed in relation to this issue, but do not understand what effect it all has.  Seems like mostly test code.  What functionality did you change in the API?  You suggested earlier that owsExceptionReport.xsd was missing from owsAll.xsd.  Did you add it?  If so, what effect did it have?

**Comment by highsource** [comment]
No effect. I only added a few tests, no changes to the runtime code.

I *thought* `owsExceptionReport.xsd` was missing, but I was wrong; It is in `owsAll.xsd`.

So basically the changes have no runtime effect (everything is as it was), I effectively only added a few tests.
