### ISSUE TITLE
Error compiling WMC 1.0.0

### ISSUE THREAD

**Issue by tastle** [highsource/ogc-schemas#72]
I did a pull and started clean.

mvn clean package

[ERROR] Error while parsing schema(s).Location [ http://schemas.opengis.net/context/1.0.0/collection.xsd{34,13}].
org.xml.sax.SAXParseException; systemId: http://schemas.opengis.net/context/1.0.0/collection.xsd; lineNumber: 34; columnNumber: 13; 'OnlineResourceType' is already defined

[ERROR] Error while parsing schema(s).Location [ http://schemas.opengis.net/context/1.0.0/context.xsd{158,44}].
org.xml.sax.SAXParseException; systemId: http://schemas.opengis.net/context/1.0.0/context.xsd; lineNumber: 158; columnNumber: 44; (related to above error) the first definition appears here

**Comment by highsource** [comment]
Should be fixed now.
