### ISSUE TITLE
Ability to Marshall / Unmarshall SLD_1_1_0

### ISSUE THREAD

**Issue by 1Map** [highsource/ogc-schemas#78]
It would be really nice to Marshall / Unmarshall SLD 1.1.0, see: 

https://github.com/highsource/ogc-schemas/issues/76

**Comment by highsource** [comment]
Almost done. There's a namespace conflict between WMS 1.3.0 exception report and Filter 1.1.0. So #86 is blocking.

TODOs:
* Add wms 1.3.0 as dependency when #86.
* Tests in scripts.

**Comment by highsource** [comment]
Done, see the following test:

* https://github.com/highsource/ogc-schemas/tree/master/scripts/tests/SLD/1.1.0
