### ISSUE TITLE
<ogc:Function name="offset"> is not picked up within symbolizer's geometry part

### ISSUE THREAD

**Issue by 1Map** [highsource/ogc-schemas#85]
I have the following XML:

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<sld:StyledLayerDescriptor xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:uom="http://www.opengeospatial.org/se/units/metre" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0">
    <sld:NamedLayer>
        <sld:Name>Custom Style</sld:Name>
        <sld:UserStyle>
            <sld:Title>Default custom style</sld:Title>
            <sld:Abstract>A sample style</sld:Abstract>
            <sld:FeatureTypeStyle>
                <sld:Rule>
                    <sld:Name>Polygon</sld:Name>
                    <sld:Title>Polygon Rule</sld:Title>
                    <sld:Abstract>Default Style for Polygons</sld:Abstract>
                    <sld:MinScaleDenominator>0</sld:MinScaleDenominator>
                    <sld:MaxScaleDenominator>1</sld:MaxScaleDenominator>
                    <sld:PolygonSymbolizer>
                        <sld:Geometry>
                            <ogc:Function name="offset">
                                <ogc:PropertyName>the_geom</ogc:PropertyName>
                                <ogc:Literal>0.00004</ogc:Literal>
                                <ogc:Literal>-0.00004</ogc:Literal>
                            </ogc:Function>                      
                        </sld:Geometry>
                        <sld:Fill>
                            <sld:CssParameter name="fill">#AAAAAA</sld:CssParameter>
                        </sld:Fill>
                        <sld:Stroke>
                            <sld:CssParameter name="stroke">#000000</sld:CssParameter>
                            <sld:CssParameter name="stroke-width">1</sld:CssParameter>
                        </sld:Stroke>
                    </sld:PolygonSymbolizer>
                </sld:Rule>
            </sld:FeatureTypeStyle>
        </sld:UserStyle>
    </sld:NamedLayer>
</sld:StyledLayerDescriptor>
```

By unmarshalling, the JSON does not contain the ogc:Function part within the geometry.  Geometry only contains:

```json
{
    TYPE_NAME: "SLD_1_0_0.Geometry"
}
```

**Comment by highsource** [comment]
As far as I can see, SLD 1.0.0 does not support `ogc:Function` in `sld:Geometry`:

https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources-original/ogc/sld/1.0.0/StyledLayerDescriptor.xsd#L287-L299

```xml
	<xsd:element name="Geometry">
		<xsd:annotation>
			<xsd:documentation>
        A Geometry gives reference to a (the) geometry property of a
        feature to be used for rendering.
      </xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="ogc:PropertyName"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
```

Your XML seems to be not SLD 1.0.0 compliant. Which schema are you using? Are these some vendor extensions?

**Comment by highsource** [comment]
Function in geometry seems to be an SLD 1.1.0/SE 1.1.0 feature.

**Comment by 1Map** [comment]
Sorry,

My fault.  This is a Geoserver Extension:

SLD 1.0 requires the <Geometry> content to be a <ogc:PropertyName>. GeoServer extends this to allow a general SLD expression to be used. The expression can contain filter functions that manipulate geometries by transforming them into something different. This facility is called SLD geometry transformations.

GeoServer provides a number of filter functions that can transform geometry. A full list is available in the Filter Function Reference (See offset under Geometric Functions - http://docs.geoserver.org/stable/en/user/filter/function_reference.html#filter-function-reference)

**Comment by highsource** [comment]
You can either extend the mappings (they're just JSON so you can modify then) or I'd be actually OK to patch the SLD 1.0.0 schemas. I think this is a reasonable extension and it is not incompatible to the original SLD 1.0.0, so I think that'd be acceptable.

Alternatively we could compile `SLD_1_0_0_GeoServer` etc.

If you'd send me a PR with changes to this file:

https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources/ogc/sld/1.0.0/StyledLayerDescriptor.xsd

I'd be able to implement it. And an issue to track it, please.

**Comment by 1Map** [comment]
Will do so, thanks highsource....

**Comment by 1Map** [comment]
See: Geoserver's StyledLayerDescriptor

https://github.com/geoserver/geoserver/blob/master/src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd

**Comment by highsource** [comment]
Ok, this is a good input. Please file an issue for SLD 1.0.0 GeoServer dialect.

**Comment by 1Map** [comment]
There are Geoserver related stuff, for example....

The standard SLD_1_0_0

```xml
<xsd:element name="Geometry">
      <xsd:annotation>
            <xsd:documentation>
                  A Geometry gives reference to a (the) geometry property of a
                  feature to be used for rendering.
            </xsd:documentation>
      </xsd:annotation>
      <xsd:complexType>
            <xsd:sequence>
                  <xsd:element ref="ogc:PropertyName"/>
            </xsd:sequence>
      </xsd:complexType>
</xsd:element>
```

The SLD_1_0_0_Geoserver

```xml
<xsd:element name="Geometry">
      <xsd:annotation>
            <xsd:documentation>
                  A Geometry gives reference to a (the) geometry property of a
                  feature to be used for rendering.
            </xsd:documentation>
      </xsd:annotation>
      <xsd:complexType>
            <xsd:sequence>
                  <xsd:element ref="ogc:expression"/>
            </xsd:sequence>
      </xsd:complexType>
</xsd:element>
```

What do you think should be the easiest and most compatible so it can work with Geoserver as well as the standard SLD_1_0_0 ?

**Comment by highsource** [comment]
I'll make a diff and see what's different. If diff does not show incompatibilities then you could use SLD_1_0_0_GeoServer for GeoServer as well as standard, Just don't use GeoServer-specific features with unsupporting servers. These will be different modules (.js files) but the same mapping name (SLD_1_0_0).

**Comment by 1Map** [comment]
Appreciate all your input Alexey. You do some excellent work.

**Comment by highsource** [comment]
Thank you for your feedback. :) This keeps me going.

I'm closing this issue and continuing in #87.
