### ISSUE TITLE
Support for Geoserver Vendor Specific SLD 1.0.0

### ISSUE THREAD

**Issue by 1Map** [highsource/ogc-schemas#87]
Would be nice to have Geoserver related SLD 1.0.0 - Also see: https://github.com/highsource/ogc-schemas/issues/85#issuecomment-93245349

For Geoserver, see: https://github.com/geoserver/geoserver/blob/master/src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd

There are Geoserver related stuff, for example....

The standard SLD_1_0_0

```xml
<xsd:element name="Geometry">
      <xsd:annotation>
            <xsd:documentation>
                  A Geometry gives reference to a (the) geometry property of a
                  feature to be used for rendering.
            </xsd:documentation>
      </xsd:annotation>
      <xsd:complexType>
            <xsd:sequence>
                  <xsd:element ref="ogc:PropertyName"/>
            </xsd:sequence>
      </xsd:complexType>
</xsd:element>
```

The SLD_1_0_0_Geoserver

```xml
<xsd:element name="Geometry">
      <xsd:annotation>
            <xsd:documentation>
                  A Geometry gives reference to a (the) geometry property of a
                  feature to be used for rendering.
                  As a GeoServer specific extensions all expressions are actually accepted.
            </xsd:documentation>
      </xsd:annotation>
      <xsd:complexType>
            <xsd:sequence>
                  <xsd:element ref="ogc:expression"/>
            </xsd:sequence>
      </xsd:complexType>
</xsd:element>
```

**Comment by highsource** [comment]
Ok, so I did a diff.

On the XML level schemas seem to be compatible, so if you marshal with `SLD_1_0_0_GeoServer` but don't use GeoServer extensions, you'll get SLD 1.0.0-compatible XML.

On the JSON level there are differences. Few vendor extensions are added but some things are changed. So the JS code will not be portable between `SLD_1_0_0` and `SLD_1_0_0_GeoServer`, you'll have to pick one of two.

My suggestion would be to use `SLD_1_0_0_GeoServer` if you need GeoServer extensions. You can still produce standard SLD 1.0.0 XML with it.

**Comment by highsource** [comment]
This is done now, please see this test:

* https://github.com/highsource/ogc-schemas/blob/master/scripts/tests/SLD/1.0.0-geoserver/SLD_1_0_0_GeoServer.js

Especially your example:

* https://github.com/highsource/ogc-schemas/blob/master/scripts/tests/SLD/1.0.0-geoserver/example-geoserver-sld.xml

**Comment by 1Map** [comment]
Wow that was quick, excellent.... I tested and it works 100%, Thanks

**Comment by 1Map** [comment]
Thanks, SLD_1_0_0_GeoServer.js is working fine, but I am missing: SLD_1_1_0_GeoServer.js

**Comment by highsource** [comment]
Please file an issue. :)

Any chance you could do it on your own an send me a PR? Would be really helpful as I'm currenlty very busy preparing http://deutschebahn.com/hackathon...
