### ISSUE TITLE
Parsing OGC WMS capabilities doesn't manage a collection of "layer"

### ISSUE THREAD

**Issue by ThomasG77** [highsource/ogc-schemas#90]
I retrieve an XML from this MapServer [url](http://geoservices.brgm.fr/geologie?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities) and save it as `brgm_sample.xml`

Then, I use below code in a `wms_test.js` file

```
var Jsonix = require('jsonix').Jsonix;
var XLink_1_0 = require('w3c-schemas').XLink_1_0;
var OWS_1_1_0 = require('ogc-schemas').OWS_1_1_0;
var WMS_1_3_0 = require('ogc-schemas').WMS_1_3_0;

var toUnmarshal = [
  XLink_1_0,
  OWS_1_1_0,
  WMS_1_3_0
];

var context = new Jsonix.Context(toUnmarshal, {
  namespacePrefixes: {
    'http://www.w3.org/1999/xlink': 'xlink',
    'http://www.opengis.net/wms': 'wms',
    'http://www.opengis.net/ows/1.1': 'ows'
  }
});
var unmarshaller = context.createUnmarshaller();

unmarshaller.unmarshalFile('data/brgm_sample.xml', function(result) {
  console.log(JSON.stringify(result, null, '  '));
});
```
and run

    node wms_test.js

If you debug, you will see that `result.value.capability.layer` only reference a layer with a name `MINES` whereas we should get a layer with a collection of layer because a capability can have 0 to n layer blocks.

For this reason, we should also get layers with names `GEOSERVICES_GEOLOGIE` and `GITES` but both were overwritten by `MINES` (search mentioned strings in the original XML if I'm not clear enough).

**Comment by highsource** [comment]
According to the [WMS 1.3.0 schema](http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd) (see [here](https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources-original/ogc/wms/1.3.0/capabilities_1_3_0.xsd#L201)), `Layer` in `Capability` is not repeatable:

```xml
	<!-- ********************************************************************* -->
	<!-- **  The Capability Element.                                        ** -->
	<!-- ********************************************************************* -->
	<element name="Capability">
		<annotation>
			<documentation>
        A Capability lists available request types, how exceptions may be
        reported, and whether any extended capabilities are defined.
        It also includes an optional list of map layers available from this
        server.
      </documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="wms:Request"/>
				<element ref="wms:Exception"/>
				<element ref="wms:_ExtendedCapabilities" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="wms:Layer" minOccurs="0"/>
			</sequence>
		</complexType>
	</element>
```

So the MapServer delivers invalid WMS GetCapabilities response.

**Comment by ThomasG77** [comment]
I didn't expect this. I clearly assumed MapServer was fully WMS 1.3.0 compliant since a long time >> https://trac.osgeo.org/mapserver/wiki/MapServerOGCCITECompliance#WMS1.3.0

Folks at @mapserver, @rouault @tbonfort any clue about this behaviour? History, error, normal?

**Comment by highsource** [comment]
I'd suggest to file an issue in @mapserver.

From the `ogc-schemas` side options are:

* Patch the main WMS 1.3.0 schema.
* Provide a WMS 1.3.0 "MapServer" version.
* Fix the mapping manually before instantiating the context.

The third option is a workaround you can do at the moment.

**Comment by tbonfort** [comment]
cc @gsueur : can you confirm that this document is not generated by mapserver but by another means?

**Comment by highsource** [comment]
@gsueur @tbonfort @mapserver Any update on this? I just need to know if there's a MapServer dialect of WMS Capabilities - with repeatable `Layer` on the top level.

If there's not, then I'd close this issue.

**Comment by ThomasG77** [comment]
Looking at [MapServer demo](http://demo.mapserver.org/), I didn't see the issue here I raise in the issue.
Let's consider that there are no repeatable `Layer` on the top level and it's an issue on the BRGM side because a MapServer specific `getCapabilities` request normally send in the XML as a comment something like below (and it's not here)

```
<!-- MapServer version 6.4.1 OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WFS_SERVER SUPPORTS=WCS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE -->
```

I close the issue and will reopen the issue if necessary.
