### ISSUE TITLE
Add support for WMS-C

### ISSUE THREAD

**Issue by bartvde** [highsource/ogc-schemas#91]
See: http://wiki.osgeo.org/wiki/WMS_Tile_Caching

This is basically WMS 1.1.1 with a few items added (cited from the DTD, btw how does JSONIX work with DTDs?):

```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE WMT_MS_Capabilities SYSTEM "http://mapstory.org:80/geoserver/schemas/wms/1.1.1/WMS_MS_Capabilities.dtd"[
<!ELEMENT VendorSpecificCapabilities (TileSet*) >
<!ELEMENT TileSet (SRS, BoundingBox?, Resolutions, Width, Height, Format, Layers*, Styles*) >
<!ELEMENT Resolutions (#PCDATA) >
<!ELEMENT Width (#PCDATA) >
<!ELEMENT Height (#PCDATA) >
<!ELEMENT Layers (#PCDATA) >
<!ELEMENT Styles (#PCDATA) >
]>
```

**Comment by highsource** [comment]
Yes, the schema compiler can compile DTDs.

So do I get it right that it's this DTD: http://mapstory.org:80/geoserver/schemas/wms/1.1.1/WMS_MS_Capabilities.dtd
Plus those extensions you've posted?

**Comment by bartvde** [comment]
Right it should be the normal 1.1.1 DTD with those extensions, see also: http://wiki.osgeo.org/wiki/WMS_Tiling_Client_Recommendation#Internal_DTD

**Comment by highsource** [comment]
OK, doable.

**Comment by bartvde** [comment]
If you need an example output, here is one: http://mapstory.org/geoserver/geonode/PB_Business_Sites/wms?request=GetCapabilities&TILED=TRUE&version=1.1.1

**Comment by highsource** [comment]
Very good, thank you.

**Comment by bartvde** [comment]
@highsource any chance this might get implemented? TIA.

**Comment by highsource** [comment]
It will, I'm just under huge stress at the moment. Stay tuned. This is not even a big thing, few DTDs are compiled already.

**Comment by highsource** [comment]
@bartvde Should be done now. Please let me know if it works for you.

**Comment by bartvde** [comment]
Thanks @highsource, I'll test this out soon (early this week).

**Comment by bartvde** [comment]
works like a charm @highsource thanks again

**Comment by highsource** [comment]
I'm glad, thanks for the feedback.
