### ISSUE TITLE
Fix typed:false in CSW_2_0_2

### ISSUE THREAD

**Issue by highsource** [highsource/ogc-schemas#94]
https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/CSW_2_0_2.js#L820

Origin: highsource/jsonix#84.

**Comment by juanmav** [comment]
@highsource A question: can be a temporaly solution to change `typed: false` to `typed: true` or is needed more changes ?

**Comment by highsource** [comment]
Yes, that'd be a temporal solution. For the correct long-term solution, I'll have to customize the generation.

**Comment by juanmav** [comment]
@highsource Another line to be fix is https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/CSW_2_0_2.js#L750

to get the FilterCapabilities

Thanks
JM

**Comment by highsource** [comment]
Should be fixed now.

**Comment by juanmav** [comment]
@highsource could we have a 2.2.1 tag with this fix ? So I can update the ows.js 's  dependencies

Thanks in advance
JM

**Comment by juanmav** [comment]
@highsource Another problem is in https://github.com/highsource/ogc-schemas/blob/2.2.0/scripts/lib/CSW_2_0_2.js#L507 (Tag 2.2.0 not the master)

To get the record object in the Insert Transaction. I am not sure with your fix this were fixed too.

Thanks
JM

**Comment by juanmav** [comment]
An example of this: http://jsfiddle.net/juanmav/kom1qhj6/3/

**Comment by highsource** [comment]
Yes, it was:

https://github.com/highsource/ogc-schemas/blob/master/csw/2.0.2/src/main/resources/csw-v_2_0_2.xjb#L21

I basically did a fullt-text search and the fixed suspicious places. There were, like a dozen of problems of this kind. Fixed most of them, left a couple which were so defined in schemas.

I'd love to release but need to release Jsonix first which has highsource/jsonix#73 still in the pipeline.
And we have to fix bower.json first as well.

**Comment by juanmav** [comment]
@highsource I just saw you closed the highsource/jsonix#73 some days ago. Maybe we could have  a new tag the [2.2.1](https://github.com/highsource/ogc-schemas/milestones/2.2.1)?

I am a little eager to merge some features [branchs](https://github.com/juanmav/ows.js/network) at [ows.js](https://github.com/juanmav/ows.js) :P

Thanks
JM

**Comment by highsource** [comment]
@juanmav 2.3.0 is released now, please give it a try.

**Comment by juanmav** [comment]
@highsource Sorry for the delay, now it is working ok! Thanks.
