### ISSUE TITLE
Error while creating a SOS_1_0_0 context

### ISSUE THREAD

**Issue by htulipe** [highsource/ogc-schemas#95]
Hi,

I compiled the project to get js mapping for SOS document, I got an error when doing this:

    var context = new Jsonix.Context([SOS_1_0_0]);

The error is:

    Type info [SOS_1_0_0_Filter.TemporalOpsType] is not known in this context.

I saw that mappings declare dependencies. In this case :

    var SOS_1_0_0_Module_Factory = function () {
      var SOS_1_0_0 = {
       n: 'SOS_1_0_0',
       dens: 'http:\/\/www.opengis.net\/sos\/1.0',
       deps: ['OWS_1_1_0', 'GML_3_1_1', 'SWE_1_0_1', 'SOS_1_0_0_Filter', 'OM_1_0_0'],
       ...
    }

Including `SOS_1_0_0_Filter.js` in my html did not fix the issue. What do I need to do to satisfy mapping dependencies?

Thanks in advance.

**Comment by highsource** [comment]
`deps` are not considered at the moment, it's for information purposes only. You'll have to declare all the required mappings, see here:

https://github.com/highsource/ogc-schemas/blob/master/scripts/tests/SOS/1.0.0/SOS_1_0_0.js

**Comment by htulipe** [comment]
Okay thanks for the link.
